### PR TITLE
Fix ZeroDivisionError

### LINKED ISSUE #8: ZeroDivisionError: division by zero on API calls
Hi,

When running some tests with kytos_stats, I found this error:

```
        api_url = KYTOS_STATS + f'/bytes_count/{flow_id}'
        response = requests.get(api_url)
>       assert response.status_code == 200, response.text
E       AssertionError: Traceback (most recent call last):
E           File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 162, in __call__
E             await self.app(scope, receive, _send)
E           File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 84, in __call__
E             await self.app(scope, receive, send)
E           File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
E             raise exc
E           File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
E             await self.app(scope, receive, sender)
E           File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 716, in __call__
E             await route.handle(scope, receive, send)
E           File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 276, in handle
E             await self.app(scope, receive, send)
E           File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 68, in app
E             response = await run_in_threadpool(func, request)
E           File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
E             return await anyio.to_thread.run_sync(func, *args)
E           File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
E             return await get_asynclib().run_sync_in_worker_thread(
E           File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
E             return await future
E           File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
E             result = context.run(func, *args)
E           File "//var/lib/kytos/napps/amlight/kytos_stats/main.py", line 130, in bytes_count
E             flow.stats.byte_count * 8 / flow.stats.duration_sec
E         ZeroDivisionError: division by zero
E
E       assert 500 == 200
E        +  where 500 = <Response [500]>.status_code
```

the test consists basically of installing a flow, waiting around 20 seconds and calling the API `/amlight/kytos_stats/v1/bytes_count/{flow_id}` (of_core.STATS_INTERVAL configured to 7 seconds)

### PR DESCRIPTION
**Pull request by gretelliz**
Closes #8 

### Summary

This is to avoid the error due to division by zero when `duration_sec` is zero in the `stats`.
In this case, the value zero is assumed.

### CODE REVIEW

**Review by viniarck — CHANGES_REQUESTED** [review]
Looks good, but the changelog hasn't been updated.

**Review by viniarck — APPROVED** [review]
LGTM

**Review by italovalcy — APPROVED** [review]
Excellent, @gretelliz ! LGTM. Can you please provide a backport to 2023.1?

**Comment by viniarck** [comment]
I'll go ahead and merge this. @gretelliz check out, Italo's backport comment though.

**Pull request merged**
